import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { NextAuthProvider } from '@/components/Providers'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'BlogSpace',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link rel='icon' href='/blogging.png' />
      </head>
      <body className={`bg-cover bg-center ${inter.className}`} style={{ backgroundImage: `url("/Contour Line.svg")` }}>  
      <NextAuthProvider>   
        <div className="lg:max-w-[900px] lg:px-16 mx-auto px-8 py-8 shadow-2xl min-h-screen flex flex-col">
          <Navbar />
          <div className='flex-auto'>{children}</div>
          <Footer />
        </div>
        <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  )
}
